kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/oliver006/redis_exporter


services:
  - name: redis5
    image: redis:5
    commands:
      - "redis-server --port 6383  --dbfilename dump5.rdb"
    ports:
      - 6383

  - name: redis6
    image: redis:6
    commands:
      - "redis-server --protected-mode no --dbfilename dump6.rdb"
    ports:
      - 6379

  - name: pwd-redis5
    image: redis:5
    commands:
      - "redis-server --port 6380 --requirepass redis-password --dbfilename dump5-pwd.rdb"
    ports:
      - 6380

  - name: pwd-redis6
    image: redis:6
    commands:
      - "redis-server --port 6390 --requirepass dummy --user exporter on +INFO +CLIENT +SELECT +SLOWLOG +LATENCY '>exporter-password' --dbfilename dump6-pwd.rdb"
    ports:
      - 6390

  - name: redis-2-8
    image: redis:2.8
    commands:
      - "redis-server --port 6381 --dbfilename dump2-8.rdb"
    ports:
      - 6381

  - name: keydb-01
    image: "eqalpha/keydb:x86_64_v5.3.0"
    commands:
      - "keydb-server --protected-mode no --port 6401 --dbfilename dump-keydb-01.rdb"
    ports:
      - 6401

  - name: keydb-02
    image: "eqalpha/keydb:x86_64_v5.3.0"
    commands:
      - "keydb-server --protected-mode no --port 6402 --active-replica yes --replicaof keydb-01 6401  --dbfilename dump-keydb-02.rdb"
    ports:
      - 6402

  - name: redis-cluster
    image: grokzen/redis-cluster
    ports: [ 7000, 7001, 7002, 7003, 7004, 7005 ]

  - name: tile38
    image: tile38/tile38:latest
    ports:
      - 9851


steps:
  - name: start
    image: "golang:1.16"
    commands:
      - sleep 10
      - 'echo "start"'
    when:
      event:
        - pull_request
        - push
        - tag

  #
  # starting this service down here using "detached: true" because it depends on
  # the "redis6" service and it intermittently fails if that service is not available yet
  # making it start after the "start" step which waits 10 seconds hopefully fixes that issue
  #
  - name: redis-sentinel
    image: "docker.io/bitnami/redis-sentinel:6.2-debian-10"
    environment:
      REDIS_MASTER_HOST: redis6
    ports:
      - 26379
    detach: true
    when:
      event:
        - pull_request
        - push
        - tag
    depends_on:
      - start

  - name: build-binaries
    image: "golang:1.16"
    pull: always
    environment:
      GO111MODULE: on
      LOG_LEVEL: "info"
    commands:
      - make build-binaries
    when:
      event:
        - pull_request
        - push
        - tag
    depends_on:
      - start

  - name: test-docker-build
    image: plugins/docker
    settings:
      tags: "test"
      dockerfile: ./docker/Dockerfile.amd64
      repo: oliver006/redis_exporter
      target: scratch
      dry_run: true
      build_args:
        - 'TAG=test'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=amd64'
      username:
        from_secret: docker_test_user
      password:
        from_secret: docker_test_pass
    when:
      event:
        - pull_request
        - push
        - tag
    depends_on:
      - start

  - name: lint
    image: golangci/golangci-lint:latest-alpine
    pull: always
    commands:
      - apk add --update make
      - make lint
    when:
      event:
        - pull_request
        - push
        - tag
    depends_on:
      - start

  - name: tests
    image: "golang:1.16"
    pull: always
    environment:
      GO111MODULE: on
      LOG_LEVEL: "info"
      COVERALLS_TOKEN:
        from_secret: coveralls-token
    commands:
      - sleep 5
      - make checks
      - make test
      - make upload-coverage
    when:
      event:
        - pull_request
        - push
    depends_on:
      - build-binaries


  - name: mixins
    image: golang:1.16
    commands:
      - cd ./contrib/redis-mixin
      - go install github.com/monitoring-mixins/mixtool/cmd/mixtool
      - go install github.com/google/go-jsonnet/cmd/jsonnetfmt
      - cd ../../
      - make mixin
    when:
      event:
        - pull_request
        - push
    depends_on:
      - start


  - name: coverage-codecov
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - coverage.txt
    when:
      event:
        - pull_request
        - push
    depends_on:
      - tests


  - name: release-docker-image-scratch
    image: plugins/docker
    settings:
      tags: "latest,latest-amd64,${DRONE_TAG},${DRONE_TAG}-amd64"
      dockerfile: ./docker/Dockerfile.amd64
      repo: oliver006/redis_exporter
      target: scratch
      build_args:
        - 'TAG=${DRONE_TAG}'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=amd64'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - tag
    depends_on:
      - tests


  - name: release-docker-image-alpine-arm64
    image: plugins/docker
    settings:
      tags: "latest-arm64,${DRONE_TAG}-arm64"
      dockerfile: ./docker/Dockerfile.arm64
      repo: oliver006/redis_exporter
      target: alpine-arm64
      build_args:
        - 'TAG=${DRONE_TAG}'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=arm64'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - tag
    depends_on:
      - tests


  - name: release-docker-image-alpine-arm
    image: plugins/docker
    settings:
      tags: "latest-arm,${DRONE_TAG}-arm"
      dockerfile: ./docker/Dockerfile.arm
      repo: oliver006/redis_exporter
      target: alpine-arm
      build_args:
        - 'TAG=${DRONE_TAG}'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=arm'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - tag
    depends_on:
      - tests


  - name: release-docker-image-alpine-amd64
    image: plugins/docker
    settings:
      tags: "alpine,${DRONE_TAG}-alpine"
      dockerfile: ./docker/Dockerfile.amd64
      repo: oliver006/redis_exporter
      target: alpine
      build_args:
        - 'TAG=${DRONE_TAG}'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=amd64'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - tag
    depends_on:
      - tests


  - name: release-github-binaries
    image: "golang:1.16"
    pull: always
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GO111MODULE: on
    commands:
      - "apt-get update && apt-get install -y zip"
      - "./release-github-binaries.sh"
    when:
      event:
        - tag
    depends_on:
      - tests
      - build-binaries
