version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -ST1023
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: "github.com/rclone/rclone/cmd/serve/httplib" is deprecated'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
