name: PR lint

on: 
  pull_request:
    branches:
      - master
      - 'production_*'

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@v1.0.4
      with:
        title-regex: '^.*SNOW-\d*.*'
        title-regex-flags: 'g'
