{
 "title": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(redis_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Commands per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_total{instance=\"$instance\"} [1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command latency per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=\"$instance\"}[1m])) by (cmd)\n  /\nsum(irate(redis_commands_total{instance=\"$instance\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hit ratio",
   "type": "graph",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=\"$instance\"}[1m]) / (irate(redis_keyspace_misses_total{instance=\"$instance\"}[1m]) + irate(redis_keyspace_hits_total{instance=\"$instance\"}[1m]))",
     "legendFormat": "Hit ratio"
    },
    { "expr": "1", "legendFormat": "Target hit ratio for cache" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "redis_memory_max_bytes{instance=\"$instance\"}",
     "legendFormat": "Configured max memory"
    },
    {
     "expr": "redis_memory_used_rss_bytes{instance=\"$instance\"}",
     "legendFormat": "Used RSS memory"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_memory_fragmentation_ratio{instance=\"$instance\"}"
    },
    { "expr": "1.5", "legendFormat": "Recommend redis restart" }
   ]
  },
  {
   "title": "Key evictions per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{instance=\"$instance\"}[1m])",
     "legendFormat": "Evictions"
    }
   ]
  },
  { "title": "Basic activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "redis_blocked_clients{instance=\"$instance\"}",
     "legendFormat": "Clocked"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=\"$instance\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=\"$instance\"}) by (instance) - sum (redis_db_keys_expiring{instance=\"$instance\"}) by (instance)",
     "legendFormat": "not expiring, {{ instance }}"
    },
    {
     "expr": "sum(redis_db_keys_expiring{instance=\"$instance\"}) by (instance)",
     "legendFormat": "expiring, {{ instance }}"
    }
   ]
  },
  {
   "title": "Connected slaves",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_slaves{instance=\"$instance\"}",
     "legendFormat": "Connected slaves"
    }
   ]
  },
  {
   "title": "Time since last master connection",
   "type": "graph",
   "description": "This metric is only exported if the instance is a slave.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{instance=\"$instance\"}"
    }
   ]
  }
 ]
}