name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ build ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch you want to build'
        required: true
        default: 'build'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        docker: ['scratch','ubi']
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: ${{ matrix.docker }}
    steps:
    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_UBI_READONLY_USERNAME }}
        password: ${{ secrets.QUAY_UBI_READONLY_PASSWORD }}
    - name: build
      uses: sysdiglabs/exporter-builder@v1.2
      with:
        exporter: redis-exporter
        artifactory_token: ${{ secrets.GAR_DEV_RW_JSON_KEY }}
        artifactory_username: _json_key
        sysdig_secure_token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        tag_name: dev
        target: ${{ matrix.docker }}
        repository: us-docker.pkg.dev
